name: Run the tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run linters
        run: |
          pip3 install -U micropython-unix-stubs --no-user --target ./.typings
          pip3 install mypy==1.16.1 ruff==0.12.1
          ruff check
          mypy
